project_id = "vbbpwyekwpnbyygdxxlq"

[functions.send-invite]
verify_jwt = true

[functions.advance-workflow]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.interpret-drawing]
verify_jwt = false
